#!/usr/bin/perl
use Term::ANSIColor;
use strict;

my $cell = shift;

#- Options: --short for one line output, --noprop to ignore property
#- errors. The flat LVS flow resolves symmetric gates by their
#- properties, which netgen flags as property errors even when every
#- itemized property matches, so a flat flow passes --noprop and
#- relies on the hierarchical per cell runs for property checking.
my $doShort = 0;
my $doProp = 1;
foreach my $opt (@ARGV ? () : ()){}
while(my $arg = shift){
  $arg =~ s/\s+//ig;
  $doShort = 1 if($arg eq "--short");
  $doProp  = 0 if($arg eq "--noprop");
}


my $ok = 0;
my $match = 0;
my $propOk = 1;
while(<>){
  if(!$doShort){
      print $_;
  }

  if(m/match uniquely/ig){
    $match = 1;
  }
  if(m/the following cells had property errors/ig){
     $propOk = 0;
  }
  if(m/Property errors were found/ig){
     $propOk = 0;
  }
  if(m/failed pin matching/ig){
     $propOk = 0;
  }
  if(m/Final result: Netlists do not match/){
    $match = 0;
  }
  if(m/Final result: Circuits match uniquely/){
    $match = 1;
  }
}

my $message = "";
if(!$match){
  $message .= " Warning: Circuits do not match\n";
}

if(!$doProp){
  $propOk = 1;
}

if(!$propOk){
  $message .= " Error: Property errors\n";
}

if(!$match || !$propOk){
  $message .= " Warning: Check log for details\n";
}

my $smiley = <<EOF;

##################################
#                _   _           #
#                \$   \$           #
#   CORRECT        |             #
#                \\___/           #
#                                #
##################################
EOF

my $error = <<EOF;
##################################
#                 _   _          #
#                 x   x          #
#  INCORRECT        |            #
#                  ___           #
#                                #
##################################
$message
EOF


my $shortstart = sprintf("%-40s\t[ ",$cell);
my $shortend = " ]\n";

my $exit = 0;
if($match && $propOk){
  if(!$doShort){
    print($smiley);
  }else{
    print($shortstart.color('green').'LVS OK  '.color('reset').$shortend);
  }
}else{
  $exit = 1;
  if(!$doShort){
    print($error);
  }else{
    print($shortstart.color('red').'LVS FAIL'.color('reset').$shortend)
  }
}

exit $exit;
