#!/usr/bin/perl
use strict;

my $file = shift;
my $lib = shift;
open(my $fh, "<", $file) || die "Could not open $file";

while(<$fh>){
  if(m/_mdl\.sv/){
    s/_mdl\.sv//ig;
    s/^\s+//ig;
    my @ar = split(/\s+/);
    my $name = $ar[-1];
    system("make netlist_cell LIB=$lib CELL=$name")
  }

}

close($fh) || die "Could not close $file";
