#!/usr/bin/env python3

import re
import click
import yaml
import os
import subprocess
import glob

@click.command()
@click.option("--info",default="../info.yaml",help="Default info file")
def cli(info):
    with open(info) as fi:
        obj = yaml.safe_load(fi)

    if(not os.path.exists("_results")):
        os.mkdir("_results")

    if("sim" in obj):
        for tb in obj["sim"]:
            print(f"## {tb} \n\n")
            cmd = obj["sim"][tb]
            print(f"Running `{cmd}`")
            print("```bash\n\n")
            logs = subprocess.getoutput(f"cd sim/{tb} && {cmd}")
            print(logs)
            print("```\n\n")
            htmls = glob.glob(f"sim/{tb}/results/*.html")
            for f in htmls:
                b = os.path.basename(f).replace(".html","")
                print("\n\n### " + b + "\n")
                print(subprocess.getoutput(f"pandoc -t gfm {f} -o -"))

            os.system(f"cp -r sim/{tb}/results _results/{tb}")






if(__name__ == "__main__"):
    cli()
